### ISSUE TITLE
Class "DeepL\TranslatorOptions" not found

### ISSUE THREAD

**Issue by matin73** [dmitryd/dd_deepl#10]
Hello,
I get error "Class "DeepL\TranslatorOptions" not found" and after enable debug:
PHP Warning: Undefined array key "settings." in /usr/www/users/ccc/xxx/typo3conf/ext/dd_deepl/Classes/Configuration/Configuration.php line 54

**Comment by dmitryd** [comment]
This extension only works in composer mode.

**Comment by dmitryd** [comment]
> PHP Warning: Undefined array key "settings." in /usr/www/users/ccc/xxx/typo3conf/ext/dd_deepl/Classes/Configuration/Configuration.php line 54

You did not add extensions's TypoScript. Please, read the manual...
