### ISSUE TITLE
Own Ctypes with IRRE

### ISSUE THREAD

**Issue by chwessalowski** [dmitryd/dd_deepl#13]
Hello Dmitry
thanks a lot for this brilliant extension. Even my own record types are all translated automagically!

Is it already possible to translate own Ctypes with IRRE elements?
If yes could you give me hint how to do so?
If not do you plan to add this feature?

Thanks a lot for you help
best regards 
  Christian Wessalowski

**Comment by chwessalowski** [comment]
Never mind. I found it out by myself.

**Comment by BrandSven** [comment]
> Never mind. I found it out by myself.

What did you do to make it work?
