### ISSUE TITLE
Glossary support

### ISSUE THREAD

**Issue by helmut-winkelbach** [dmitryd/dd_deepl#15]
Hi Dmitry, thanks for this extension.

I want to add a glossary as described here: vendor/bin/typo3 deepl:glossary info
TYPO3 12.4.11 on PHP 8.2

With pwd i get the full file path, what is in the following line:
vendor/bin/typo3 deepl:glossary add -f file.csv -g /var/www/vhosts/...jweiland-hosting.de/httpdocs/...-web.de/deepl-en-ru -s en -t ru

i get the error:  file does not exist.

Thanks a lot for you work
best regards
Helmut Winkelbach

**Comment by dmitryd** [comment]
Please, use full path to the file and a simple name of the glossary. I think it has to be like:

vendor/bin/typo3 deepl:glossary add -f /var/www/vhosts/...jweiland-hosting.de/httpdocs/...-web.de/file.csv -g deepl-en-ru -s en -t ru
