### ISSUE TITLE
add proxy-settings as parameter to deepl-api

### ISSUE THREAD

**Issue by dirnbauer** [dmitryd/dd_deepl#16]
We use TYPO3 with proxy-settings $GLOBALS['TYPO3_CONF_VARS']['HTTP']['proxy'].
the following simple patch works for me.

in Classes/Service/DeeplTranslationService.php add TranslatorOptions::PROXY,
either the value from the globals or empty.

I hope this helps. 
thanks for your great work!

```
 if (Environment::isComposerMode()) {
            $deeplOptions = array_merge(
                [
                    TranslatorOptions::SERVER_URL => $this->configuration->getApiUrl(),
                    TranslatorOptions::TIMEOUT => 10,
                    TranslatorOptions::PROXY => $GLOBALS['TYPO3_CONF_VARS']['HTTP']['proxy'] ?? '',
                ],
                $deeplOptions
            );
```

**Comment by dmitryd** [comment]
Thank you! The release will be soon.

**Comment by dirnbauer** [comment]
great, thank you!
