### ISSUE TITLE
503 Oops, an error occurred! Class "DeepL\TranslatorOptions" not found

### ISSUE THREAD

**Issue by fasnakv** [dmitryd/dd_deepl#2]
Hello, does anybody know about the error that occurs in TYPO3 12.4 on the Admin Tools page during the installation of the 'dd_deepl' extension?
503
Oops, an error occurred!
Class "DeepL\TranslatorOptions" not found

**Comment by dmitryd** [comment]
This would mean that `deeplcom/deepl-php` composer package is not installed. The extension only works in the composer mode due dependencies.

**Comment by quadronet** [comment]
Can you create a version without composer?

**Comment by dmitryd** [comment]
Sorry but no. Composer is a TYPO3 recommended way to go since TYPO3 9. We are on TYPO3 12 already. There was a lot of time to move all installations to composer.

**Comment by sbuerk** [comment]
@dmitryd Sorry, composer and non-composer mode are both officialy supported installation variants for TYPO3.

Sure, composer installations is mostly favoured by developers and it makes a lot things easier.

Releasing a extension in `TER` which cannot be run in non-composer mode. I would say a no-go. Than remove it from TER and make it clear in the README.md.

Public extension released broken in TER would raise bad habits and user experiences.

**Comment by dmitryd** [comment]
This is a free software. There are no warranties of any kind or obligations of any kind. See the license.
