### ISSUE TITLE
Translating content does not work, configuration does not contain the api key

### ISSUE THREAD

**Issue by MajPay** [dmitryd/dd_deepl#26]
I am on V11 and recently updated to 11.5.0

Translating in the page module does not work anymore. When debugging the Configuration i can see, that the typoscript setup is missing for the route `ajax/records/localize`. On other routes it works but on the localize route the typoscript is missing.

I added the static typoscript to the typoscript of the page and added the constant like described in the manual. Additionally i added the page tsconfig.

When debugging the typoscript exactly here:
https://github.com/dmitryd/dd_deepl/blob/v11.5.0/Classes/Configuration/Configuration.php#L51

the php array does not contain the "module.tx_dddeepl." It seems typo3 does not include the typoscript for that route.

When debugging further i can see, that the BackendConfigurationManager (typo3) can not determine the page uid on that route. The BackendConfigurationManager is marked as @internal btw.

**Comment by dmitryd** [comment]
I just tried with 11.5.36, I can translate.

How do you add TS to TYPO3?

**Comment by dmitryd** [comment]
No answer provided.
