### ISSUE TITLE
Unsupported content types

### ISSUE THREAD

**Issue by saitho** [dmitryd/dd_deepl#3]
Hi Dmitry,

I'm currently testing the extension. So far it really works nicely, but I noticed some areas where it does not work yet:

* `type=group`, i.e. records that are embedded into a tt_content record via relation, e.g. sys_file which can have a title override
* `pi_flexform`, which can also have flexform fields of `type=input` and `type=text`
* content elements in grids (we still use `Ext:gridelements`, have not tried `Ext:container`)

Haven't seen this mentioned in the documentation yet.

Is this something that will be integrated into this extension in the future?
I realize it is quite new. :)

Kind regards
Mario

**Comment by dmitryd** [comment]
Hi, thanks for ideas, I will check that I can do with those types. I am not sure about gridelements but container support is planned.

**Comment by dmitryd** [comment]
> type=group, i.e. records that are embedded into a tt_content record via relation, e.g. sys_file which can have a title override

Those records have to be translated by themselves, like in a normal localization process.

> content elements in grids (we still use Ext:gridelements, have not tried Ext:container)

Same here. When a nested element is translated by TYPO3, DeepL should translate it as well.
