### ISSUE TITLE
Bug when copy and paste page

### ISSUE THREAD

**Issue by Hasan-Shaker** [dmitryd/dd_deepl#32]
Hello,
I have this err when i copy and paste page.
Any one have idea ?

TYPO3 V-12
PHP : 8.2
MySQL 10.6.16-MariaDB-1:10.6.16

```

(1/1) TypeError

Dmitryd\DdDeepl\Event\CanFieldBeTranslatedCheckEvent::__construct(): 
Argument #3 ($fieldValue) must be of type string, null given, 
called in /var/www/html/vendor/typo3/cms-core/Classes/Utility/GeneralUtility.php on line 2985

```

![Cursor_et_TYPO3_Exception_·_Hug___Zollet_AG__TYPO3_CMS_12_4_14_](https://github.com/dmitryd/dd_deepl/assets/51764849/91e51eb5-d884-4c67-a10e-c6ffbf810dcc)

**Comment by dmitryd** [comment]
It should be fixed already https://github.com/dmitryd/dd_deepl/issues/30

**Comment by dmitryd** [comment]
Tested, it was fixed.
