### ISSUE TITLE
DeepL is not configured for this site

### ISSUE THREAD

**Issue by izaquieltome** [dmitryd/dd_deepl#4]
Hey guys - I have following problem:
I installed the extension - followed the integration guide.
- I added the TypoScript (By Code, because there is no option for this in "include_static_files")
- added TSpage Config for web_layout and web_list
- Added my API key 

in List and Page module I do not get the translate with deepL buttons, when I click on the Backend Module it just says "DeepL is not configured for this site". 

I use Typo3 12.4.7 in composer mode, dd-deepl 12.03. with PHP 8.1.24.
I tried every previous 12-version of deepl too - no effect.

I hope one of you can help me with this.

Thanks in advance,
Iza

**Comment by dmitryd** [comment]
Please, try updating with composer. This should be fixed.

**Comment by dmitryd** [comment]
If you put the API key directly to TS instead of the environment, you may need this also:

```
module.tx_dddeepl_ < module.tx_dddeepl
```

I will rework that part to be more independent. This is a quick fix now.

**Comment by netthinks** [comment]
does not work for me, same problem

**Comment by izaquieltome** [comment]
Still same Problem here ... unfortunately

**Comment by dmitryd** [comment]
Do you add your keys directly to TS or via environment?

Could you check that TS is actually included? See below.

![iScreen Shoter - Safari - 231031130511](https://github.com/dmitryd/dd_deepl/assets/306133/ed252566-305d-445b-9584-6b04e3203557)

**Comment by izaquieltome** [comment]
Ok - thanks for the Screenshot. That one solves the Problem.
The promble is caused by simply "copy&paste" from the MAnual from TER, where the ".settings" is missing (see screenshot attached). 
Adding the .settings before .apiKey does the magic ... -.- 
![Constants-—-TYPO3-extension-dd_deepl-12-0-documentation](https://github.com/dmitryd/dd_deepl/assets/41893913/4e198a1f-b8ab-4f46-a6a0-fa4d671087a0)

**Comment by dmitryd** [comment]
@izaquieltome Thanks a lot, I will fix this as well! 👍

**Comment by dmitryd** [comment]
> because there is no option for this in "include_static_files"

This will be fixed too in the next release.
