### ISSUE TITLE
How to configure Languages

### ISSUE THREAD

**Issue by izaquieltome** [dmitryd/dd_deepl#5]
Hey there - facing another problem (maybe not even an issue ...):

I have a site wich uses german as Main language and english and portuguese as translations.
Translating to english works perfectly fine - translating to portuguese fails - it get's the same outcome like the native translation from Typo3.

So I assume, the data for the transalation prompts are taken from the Site configuration? I wonder, if there is some "special way" to configure that languages for deepL to translate in a correct way.
I added my configurations as screenshots - maybe this helps.

![language-config-english](https://github.com/dmitryd/dd_deepl/assets/41893913/c14395c6-87b2-4d21-957e-b4a292e17471)
![language-config-portuguese](https://github.com/dmitryd/dd_deepl/assets/41893913/a7983241-35d2-4e63-9aeb-ec74d754eaaa)

**Comment by dmitryd** [comment]
Yes, it takes the language from the site configuration. Try to select locale instead of entering manually.

**Comment by izaquieltome** [comment]
You mean the Dropdown for locale? Tried this with selecting "portuguese", "pt_BR" and "pt_PT"
None of those work. 
Also tried generating a new Language Variant by selecting it from the presets - also no success.
Seems some languages are struggeling with the translation.

**Comment by dmitryd** [comment]
@izaquieltome This seems to be a deepl API issue. The fix is in Git, the release will be this week.

**Comment by kraemer-igroup** [comment]
I noticed a similar "issue" with the locale setting `en_CA`, which is a not supported DeepL target language. I added a patch to my project, so the target language falls back to en-US in this case:
```
diff --git a/Classes/Service/DeeplTranslationService.php b/Classes/Service/DeeplTranslationService.php
--- a/Classes/Service/DeeplTranslationService.php
+++ b/Classes/Service/DeeplTranslationService.php
@@ -415,6 +415,10 @@
         $languageCode = $locale->getLanguageCode();
         if ($languageCode === 'en' || $languageCode === 'pt') {
             $languageCode = str_replace('_', '-', $locale->getName());
+            // Fallback for en_CA to en-US
+            if ($languageCode === 'en-CA') {
+                $languageCode = 'en-US';
+            }
         }

         return $languageCode;
```

**Comment by dmitryd** [comment]
The fix is in the `master`, will be available in the next release.
