### ISSUE TITLE
Multi Tree meets multi language (but less languages than site config languages)

### ISSUE THREAD

**Issue by lifecounter** [dmitryd/dd_deepl#7]
I'm uncertain of the necessity of this code. Consider a scenario where there are several English variants: British (en-gb), American (en-us), a generic international version (en), and an Indian variant (en-in). In such a case, you wouldn't be able to translate from the primary language—which in my situation is 'en'—into any other language. However, once I modified the locale in the site configuration to 'de_DE.UTF-8', the translation functionality worked as expected.

Originally, the code was set up to adjust language codes for DeepL, as it sometimes requires different codes than those used by TYPO3. The original code snippet was:

so I changed the code in the DeeplTranslationService.php from

`
protected function updateLanguageCode(string $languageCode): string
    {
        return $languageCode === 'en' ? 'en-US' : $languageCode;
    }
`
    
This has been altered to:

`
protected function updateLanguageCode(string $languageCode): string
    {
        return $languageCode;
    }
`

Initially, this modification may have been sensible, but I'm contemplating whether the language code adjustment is actually causing issues in many instances. Could this be the case, or is my understanding flawed?

**Comment by dmitryd** [comment]
This will break translation to English because DeepL does not accept 'en' as a valid target language.

**Comment by lifecounter** [comment]
In my case, it appears that the DeepL translation fails when English is the primary language and there are also country-specific site variations in English. Modifying the relevant part of the code has enabled me to translate from English into all other languages.

**Comment by dmitryd** [comment]
Are you trying to translate from English to English? :) 

> Modifying the relevant part of the code has enabled me to translate from English into all other languages.

This will be fixed in the next release for v12.

**Comment by lifecounter** [comment]
I completely grasp what you are pointing out. I do not use DeepL to translate from one English variant to another. However, I encounter issues when trying to translate from English into another language if additional English language variants are involved. I am unable to identify the precise cause of the issue, but the clear outcome is that I am incapable of translating from English to any other language as long as this particular segment of code exists. For example, I cannot translate from the international English variant to Italian, but once I remove this section of code, the translation process works impeccably, allowing translations into any language. For other English variants, I proceed with the translations and remove all "translate to (...)" annotations that have been appended to the content elements.

Additionally, to offer a bit of feedback on the extension as a whole: I am a huge fan of this extension and believe that none of the previous DeepL extensions have been as precise and effective in meeting my expectations and needs.

**Comment by dmitryd** [comment]
>  I am incapable of translating from English to any other language as long as this particular segment of code exists

Yes, this was a bug because DeepL accepts only 'en' as a source language but it needs 'en-us' or 'en-gb' as a target language. Your change "fixes" it for you because your source is English :) 

This change fixes the issue: https://github.com/dmitryd/dd_deepl/commit/9db122f3f973aaf270450ec403f0e3e2b6d7cf18#diff-e453a6376fffeb6c85f596e631585347c0e3df00b3d9a121468d6bd3f91178baL276
