### ISSUE TITLE
Modal not clickable

### ISSUE THREAD

**Issue by netthinks** [dmitryd/dd_deepl#8]
When I want to create a translation, the modal is covered by a grayed-out layer. It is then not possible to click on the buttons:
![grafik](https://github.com/dmitryd/dd_deepl/assets/23073131/606734df-c20a-498b-b2dc-e2cf3079c92d)

**Comment by dmitryd** [comment]
I made the fix and it seems to work for me. If the problem happens again, reopen the ticket, please.

**Comment by kraemer-igroup** [comment]
Hi @dmitryd, sorry to comment this closed ticket. I also sometimes had the inactive modal issue and on a second try it mostly worked.

With your fix, just as info, I noticed the following:
I have a special setting, so for all "Copy" or "Translate" actions always DeepL is used and therefore I disabled the additional "Translate with DeepL" button: `mod.web_layout.localization.enableDeepL = 0`

This worked fine so far, but after your fix, the "Translate" button gets disabled in the page module when setting `mod.web_layout.localization.enableDeepL = 0`:
![image](https://github.com/dmitryd/dd_deepl/assets/10868556/6b50731b-426f-426e-b2fe-0c514edb33cb)

**Comment by dmitryd** [comment]
@kraemer-igroup I cannot really say what us going on in this case because I do not know your setup. I test on standard TYPO3. How can I reproduce this?

You have deepl ext but you disable it with settings. I do not see the logic in this...

**Comment by kraemer-igroup** [comment]
@dmitryd, yes, sorry. To reproduce: add setting `mod.web_layout.localization.enableDeepL = 0` to a subtree for example. Now the "Translate" button within the page module is disabled (not just "Translate with DeepL").

My use case: DeepL should always be used when translating page content, either with "localize" or "copyToLanguage" (I use a custom `DataHandlerTranslationHook` for this). So I do not want the additional "Translate with DeepL" option when the "Translate" button is clicked within the page module.

**Comment by dmitryd** [comment]
Strange. I only remove standard localization js in my fix and replace it with minimally updated mine.

Do you use TYPO3 12.4.7? This is now the minimum requirement.

**Comment by kraemer-igroup** [comment]
@dmitryd, yes, I use TYPO3 12.4.7 + dd_deepl 12.2.0. I did another test in a cleaner installation:

- added dd_deepl: "Translate" button is disabled in page module
- added config with DeepL API key: "Translate" button is working fine and has new option "Translate with DeepL"
- added `mod.web_layout.localization.enableDeepL = 0` setting to a page: "Translate" button is disabled:

![image](https://github.com/dmitryd/dd_deepl/assets/10868556/7d14ead6-7546-4173-b8d9-c3fd65bc455a)

It is absolutely fine, if you do not support this use case. I just (mis)used the TSConfig option of the extension for a better adjustments to my (customers) needs. If I disable the custom js, too (`templates.typo3/cms-backend.1699799468 >`), the "Translate" button is working again and the "Translate with DeepL" option is missing (as it is supposed to).

**Comment by dmitryd** [comment]
I will have a look but cannot promise the solution.

**Comment by kraemer-igroup** [comment]
@dmitryd thank you, it works perfectly! (tested with 12.4.0)
I also like your addition to translate pages, this is great!

**Comment by dmitryd** [comment]
@kraemer-igroup Great to hear that! Thanks!
