### ISSUE TITLE
Error when accessing file storages, if no page with the same uid exists

### ISSUE THREAD

**Issue by kraemer-igroup** [dmitryd/dd_deepl#9]
Hi @dmitryd,

I get this error when trying to access a file storage which ist not the default (fileadmin):
![image](https://github.com/dmitryd/dd_deepl/assets/10868556/a7b1c63d-ff60-4408-92f5-f12515f5f2ca)

The error is triggered by the following line, if I remove it (or remove the whole extensions), it works immediately:
https://github.com/dmitryd/dd_deepl/blob/master/Classes/Configuration/Configuration.php#L51

Your code looks fine too me, do you think this is a core issue? Also, there are actually no page uids 2 or 3 in this installation, while uid 1 is present. If I create a page with uid 2, it also works. But I guess, TYPO3 should not lookup page uids while requesting file storages...

**Stacktrace:**
in /var/www/html/vendor/typo3/cms-core/Classes/Utility/RootlineUtility.php line 206

```
                )
                ->executeQuery()
                ->fetchAssociative();
            if (empty($row)) {
                throw new PageNotFoundException('Could not fetch page data for uid ' . $uid . '.', 1343589451);
            }
            $this->pageRepository->versionOL('pages', $row, false, true);
            if (is_array($row)) {
                $row = $this->pageRepository->getLanguageOverlay('pages', $row, $this->context->getAspect('language'));
```

at TYPO3\CMS\Core\Utility\RootlineUtility->getRecordArray(3)
in /var/www/html/vendor/typo3/cms-core/Classes/Utility/RootlineUtility.php line 294

```
     * @throws CircularRootLineException
     */
    protected function generateRootlineCache(): void
    {
        $page = $this->getRecordArray($this->pageUid);
        // If the current page is a mounted (according to the MP parameter) handle the mount-point
        if ($this->isMountedPage()) {
            $mountPoint = $this->getRecordArray($this->parsedMountPointParameters[$this->pageUid]);
            $page = $this->processMountedPage($page, $mountPoint);
```

at TYPO3\CMS\Core\Utility\RootlineUtility->generateRootlineCache()
in /var/www/html/vendor/typo3/cms-core/Classes/Utility/RootlineUtility.php line 157

```
        }
        if (!$this->runtimeCache->has('rootline-localcache-' . $this->cacheIdentifier)) {
            $entry = $this->cache->get($this->cacheIdentifier);
            if (!$entry) {
                $this->generateRootlineCache();
            } else {
                $this->runtimeCache->set('rootline-localcache-' . $this->cacheIdentifier, $entry, [self::RUNTIME_CACHE_TAG]);
                $depth = count($entry);
                // Populate the root-lines for parent pages as well
```

at TYPO3\CMS\Core\Utility\RootlineUtility->get()
in /var/www/html/vendor/typo3/cms-extbase/Classes/Configuration/BackendConfigurationManager.php line 246

```
            'endtime' => 0,
            'sorting' => 0,
        ];
        if ($pageId > 0) {
            $rootLine = GeneralUtility::makeInstance(RootlineUtility::class, $pageId)->get();
            $sysTemplateRows = $this->sysTemplateRepository->getSysTemplateRowsByRootline($rootLine, $request);
            ksort($rootLine);
        }
        if (empty($sysTemplateRows)) {
```

at TYPO3\CMS\Extbase\Configuration\BackendConfigurationManager->getTypoScriptSetup()
in /var/www/html/vendor/dmitryd/dd-deepl/Classes/Configuration/Configuration.php line 51

```
     */
    public function __construct()
    {
        $configurationManager = GeneralUtility::makeInstance(BackendConfigurationManager::class);
        $ts = $configurationManager->getTypoScriptSetup();
        $ts = $ts['module.']['tx_dddeepl.'] ?? [];

        $contentObject = GeneralUtility::makeInstance(ContentObjectRenderer::class);
        $this->apiKey = $contentObject->stdWrap(
```

**Comment by dmitryd** [comment]
This is interesting. Thank you, I will have a look :)
